version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "kek"
      POSTGRES_PASSWORD: "lolkek"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - "CLICKHOUSE_DATABASE=db"
volumes:
  postgres-data:
  clickhouse_data: